db:
  image: mysql:5.6
  expose:
    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_USER: todo
    MYSQL_DATABASE: todobackend
    MYSQL_PASSWORD: password

agent:
  image: guto/ansible
  links:
    - db
  environment:
    PROBE_HOST: db
    PROBE_PORT: "3306"

app:
  build: ../../
  dockerfile: docker/release/Dockerfile
  links:
    - db
  volumes_from:
    - target
    - webroot 
  environment:
    DJANGO_SETTINGS_MODULE: todobackend.settings.release
    MYSQL_HOST: db
    MYSQL_USER: todo
    MYSQL_PASSWORD: password
    DEBUG: "true"
  command:
    - uwsgi
    - "--socket /var/www/todobackend/todobackend.sock"
    - "--chmod-socket=666"
    - "--module todobackend.wsgi"
    - "--master"
    - "--die-on-term"

test:
  image: guto/todobackend-specs
  links:
    - nginx
  environment:
    URL: http://nginx:8000/todos

nginx:
  build: ../../../
  dockerfile: docker-nginx/Dockerfile
  links:
    - app
  ports:
    - "8000:8000"   
  volumes_from:
    - webroot

target:
  build: ../../
  dockerfile: docker/release/Dockerfile 
  volumes:
    - /tmp/target:/wheelhouse
  entrypoint: "true"

webroot:
  build: ../../
  dockerfile: docker/release/Dockerfile
  volumes:
    - /tmp/webroot:/var/www/todobackend
  entrypoint: "true"
